### ISSUE TITLE
Resubs messages

### ISSUE THREAD

**Issue by noterei** [noterei/subsbot#1]
https://github.com/noterei/subsbot/blob/b69d235d2968e5f2d099174a617b1af08e816c14/index.js#L21

Feel free to suggest more words/phrases to be added 👇

**Comment by JRJathome** [comment]
Triforces in Aginah's cave

**Comment by noterei** [comment]
Added! https://github.com/noterei/subsbot/commit/3438126674d5eccad6df30b01624dbe868572f64
